services:
  - type: web
    name: vulnerabilidades-app
    env: dotnet
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet VulnerabilidadesApp.dll
    envVars:
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000
    plan: free
